[package]
name = "neocmakelsp"
version = "0.5.6"
edition = "2021"
license = "MIT"
description = "The Lsp for cmake"
homepage = "https://github.com/Decodetalkers/neocmakelsp"
authors = ["Decodertalkers <aakari@tutanota.com>"]
keywords = ["lsp"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[features]
#tcp = []
[dependencies]
clap = "4.1.8"
tower-lsp = "0.19.0"
lsp-types = "0.94.0"
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.16"
tree-sitter = "0.20.9"
tree-sitter-cmake = "0.2.0"
regex = "1"
once_cell = "1.17.1"
anyhow = "1.0.69"
cli-table = "0.4.7"
tracing = "0.1.37"
glob = "0.3.1"
