[package]
name = "neocmakelsp"
version = "0.8.5"
edition = "2021"
license = "MIT"
description = "The Lsp for cmake"
repository = "https://github.com/neocmakelsp/neocmakelsp"
authors = ["Decodertalkers <aakari@tutanota.com>"]
keywords = ["lsp"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
tower-lsp = "0.20.0"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.18"
tree-sitter = "0.23.0"
tree-sitter-cmake = "0.5.0"
regex = "1"
anyhow = "1.0.89"
cli-table = "0.4.9"
tracing = "0.1.40"
glob = "0.3.1"
rust-ini = "0.21.1"
ignore = "0.4.23"
toml = "0.8.19"
clap_complete = "4.5.26"
treesitter_kind_collector = "0.2.0"

[target.'cfg(windows)'.dependencies]
path-absolutize = "3.1.1"

[dev-dependencies]
tower = { version = "0.5.1", features = ["util"] }
tempfile = "3.12.0"
