[package]
name = "neocmakelsp"
version = "0.6.22"
edition = "2021"
license = "MIT"
description = "The Lsp for cmake"
homepage = "https://github.com/Decodetalkers/neocmakelsp"
authors = ["Decodertalkers <aakari@tutanota.com>"]
keywords = ["lsp"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[features]
#tcp = []
[dependencies]
clap = { version = "4.5.3", features = ["string"] }
tower-lsp = "0.20.0"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.18"
tree-sitter = "0.22.2"
tree-sitter-cmake = "0.4.3"
regex = "1"
once_cell = "1.19.0"
anyhow = "1.0.81"
cli-table = "0.4.7"
tracing = "0.1.40"
glob = "0.3.1"
rust-ini = "0.21.0"
nu-ansi-term = "0.50.0"
